ARG VERSION
FROM almalinux:"${VERSION:-9}"
ARG COURSE="DEVOPS" \
    DURATION="10HRS" \
    TRAINER="SIVAKUMAR"

CMD echo "Course: ${COURSE}, Duration: ${DURATION}, Trainer: ${TRAINER}, Version: ${VERSION}"
CMD ["sleep", "100"]